### ISSUE TITLE
Behat 3

### ISSUE THREAD

**Issue by arnaugm** [vipsoft/DoctrineDataFixturesExtension#43]
I've been using this extension for quite long time as it results pretty useful. Recently I've been trying to migrate my suites to Behat3.
Is there any plan on making it compatible with the new version?

Thanks

**Comment by arnaugm** [comment]
Sorry I was confused by the composer message, I've been able to install it using
```
"behat/symfony2-extension": "~2.0@dev",
"vipsoft/doctrine-data-fixtures-extension": "dev-master",
```
Would it be possible to use proper tags to avoid the confusion?

**Comment by stof** [comment]
@robocoder is there anything preventing to tag a 3.0 version of the extension ?

**Comment by robocoder** [comment]
@stof Not that I know of, but I haven't had time to regression test. PR welcome to update the composer dependencies to the minimum compatible version.

**Comment by Spomky** [comment]
Is there any news concerning this issue?
