### ISSUE TITLE
Custom Loader and Fixtures resolver

### ISSUE THREAD

**Issue by theofidry** [vipsoft/DoctrineDataFixturesExtension#45]
Would it be possible to somehow enable the usage of custom loaders (in charge of reading the fixtures files and persisting the generated objects) and fixtures resolver (in charge of resolving the fixtures files)?

The simplest way to achieve that IMO would be to provide interfaces and an easy way to register the loader and fixtures resolver used. This way if we're using a bundle for loading our fixtures, with a bridge, we can plug it to this extension.

Use case: using [HautelookAliceBundle](https://github.com/hautelook/AliceBundle) rather than [DoctrineFixturesBundle](https://github.com/doctrine/DoctrineFixturesBundle).

**Comment by robocoder** [comment]
It's certainly possible but it wasn't something I had in mind when crafting this extension, so it'll involve some refactoring. PRs welcome. ;)

**Comment by theofidry** [comment]
Ok glad to hear that :)
