### ISSUE TITLE
Is this repo maintained?

### ISSUE THREAD

**Issue by ruudk** [vipsoft/DoctrineDataFixturesExtension#54]
I have a hard time understanding what repository is the main one, because there is also a fork here: https://github.com/BehatExtension/DoctrineDataFixturesExtension

If this one isn't maintained anymore, could you please add a description that points to the new one?

**Comment by robocoder** [comment]
I answered a similar question in #46. I wouldn't call this repo the "main one" but it's the original one. Use whichever repo works best for you.
